In [19]:
import pandas as pd
DataFrame = pd.read_csv("C:\\Users\\adars\\OneDrive\\Attachments\\Desktop\\dataset-1 (1).csv", encoding = 'unicode_escape' )

In [35]:
import pandas as pd
from datetime import time

# Function to calculate time-based toll rates
def calculate_time_based_toll_rates(df) -> pd.DataFrame:
    """
    Calculate time-based toll rates for different time intervals within a day.

    Args:
        df (pandas.DataFrame)

    Returns:
        pandas.DataFrame
    """
    
    def get_discount_factor(day, time_val):
        weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
        weekends = ['Saturday', 'Sunday']
        
        if day in weekdays:
            if time(0, 0, 0) <= time_val <= time(10, 0, 0):
                return 0.8
            elif time(10, 0, 0) < time_val <= time(18, 0, 0):
                return 1.2
            else:
                return 0.8
        elif day in weekends:
            return 0.7
        return 1.0
    
    for index, row in df.iterrows():
        start_time = time.fromisoformat(row['startTime'])
        end_time = time.fromisoformat(row['endTime'])
        
        start_factor = get_discount_factor(row['startDay'], start_time)
        end_factor = get_discount_factor(row['endDay'], end_time)
        
        toll_columns = ['able2Hov2', 'able2Hov3', 'able3Hov2', 'able3Hov3', 'able5Hov2', 'able5Hov3', 'able4Hov2', 'able4Hov3']
        for col in toll_columns:
            if pd.notnull(row[col]) and row[col] != -1:
                df.at[index, col] *= (start_factor + end_factor) / 2
    
    df['start_day'] = df['startDay']
    df['start_time'] = pd.to_datetime(df['startTime'], format='%H:%M:%S').dt.time
    df['end_day'] = df['endDay']
    df['end_time'] = pd.to_datetime(df['endTime'], format='%H:%M:%S').dt.time
    
    return df


df = pd.read_csv("C:\Users\shri0009\Downloads\dataset-1 (1).csv")

df_with_toll_rates = calculate_time_based_toll_rates(df)

df_with_toll_rates.head()

C:\Users\adars\AppData\Local\Temp\ipykernel_12412\2617940496.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2.4000000000000004' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.at[index, col] *= (start_factor + end_factor) / 2
C:\Users\adars\AppData\Local\Temp\ipykernel_12412\2617940496.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '3.2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.at[index, col] *= (start_factor + end_factor) / 2

,id,name,id_2,startDay,startTime,endDay,endTime,able2Hov2,able2Hov3,able3Hov2,able3Hov3,able5Hov2,able5Hov3,able4Hov2,able4Hov3,start_day,start_time,end_day,end_time
0,1040000,Montgomery,-1,Monday,05:00:00,Wednesday,10:00:00,2.4,2.4,-1.0,-1.0,2.4,2.4,2.4,2.4,Monday,05:00:00,Wednesday,10:00:00
1,1040010,Black,-1,Monday,10:00:00,Friday,15:00:00,6.0,6.0,-1.0,-1.0,6.0,6.0,6.0,6.0,Monday,10:00:00,Friday,15:00:00
2,1040020,Emerald,-1,Thursday,15:00:00,Friday,19:00:00,3.0,3.0,-1.0,-1.0,3.0,3.0,3.0,3.0,Thursday,15:00:00,Friday,19:00:00
3,1040030,Foley,-1,Monday,19:00:00,Friday,23:59:59,4.8,4.8,-1.0,-1.0,4.8,4.8,4.8,4.8,Monday,19:00:00,Friday,23:59:59
4,1050000,Whittier,1050001,Saturday,00:00:00,Sunday,23:59:59,4.2,4.2,NaN,-1.0,4.2,4.2,4.2,4.2,Saturday,00:00:00,Sunday,23:59:59

In [31]:
import pandas as pd

# Sample DataFrame with 'distance' column
data = {'id_start': [1, 2, 3],
        'distance': [100, 150, 200]}
df = pd.DataFrame(data)

# Function to calculate toll rates
def calculate_toll_rate(df) -> pd.DataFrame:
    """
    Calculate toll rates for different vehicle types based on distance.

    Args:
        df (pandas.DataFrame)

    Returns:
        pandas.DataFrame
    """
    # Define the rate coefficients for each vehicle type
    rates = {
        'moto': 0.8,
        'car': 1.2,
        'rv': 1.5,
        'bus': 2.2,
        'truck': 3.6
    }
    
    # Add new columns for each vehicle type and calculate the toll rates
    df['moto'] = df['distance'] * rates['moto']
    df['car'] = df['distance'] * rates['car']
    df['rv'] = df['distance'] * rates['rv']
    df['bus'] = df['distance'] * rates['bus']
    df['truck'] = df['distance'] * rates['truck']
    
    return df

# Call the function
df_with_toll_rates = calculate_toll_rate(df)

# Display the result
df_with_toll_rates

   id_start  distance   moto    car     rv    bus  truck
0         1       100   80.0  120.0  150.0  220.0  360.0
1         2       150  120.0  180.0  225.0  330.0  540.0
2         3       200  160.0  240.0  300.0  440.0  720.0

In [37]:
import pandas as pd

def find_ids_within_ten_percentage_threshold(df, reference_id) -> pd.DataFrame:
    """
    Find all IDs whose average distance lies within 10% of the average distance of the reference ID.

    Args:
        df (pandas.DataFrame): DataFrame containing 'id_start' and 'distance' columns.
        reference_id (int): The ID to use as a reference for distance comparison.

    Returns:
        pandas.DataFrame: DataFrame with IDs whose average distance is within the specified percentage threshold
                          of the reference ID's average distance.
    """
    # Filter rows corresponding to the reference ID
    reference_rows = df[df['id_start'] == reference_id]
    
    # Check if reference_rows is empty
    if reference_rows.empty:
        print(f"No data found for reference ID {reference_id}.")
        return pd.DataFrame(columns=['id_start'])

    # Calculate the average distance for the reference ID
    reference_avg_distance = reference_rows['distance'].mean()
    
    # Calculate 10% threshold
    lower_threshold = reference_avg_distance * 0.9
    upper_threshold = reference_avg_distance * 1.1
    
    # Group by 'id_start' and calculate average distance for each ID
    grouped = df.groupby('id_start')['distance'].mean().reset_index()
    
    # Filter IDs whose average distance falls within the 10% threshold of the reference ID
    filtered_ids = grouped[(grouped['distance'] >= lower_threshold) & (grouped['distance'] <= upper_threshold)]
    
    # Sort the result by 'id_start'
    filtered_ids = filtered_ids.sort_values(by='id_start')
    
    return filtered_ids[['id_start']]

# Sample DataFrame creation for testing
data = {
    'id_start': [1, 1, 2, 2, 3, 3],
    'distance': [100, 120, 110, 115, 130, 140]
}
df = pd.DataFrame(data)

# Call the function with a reference ID
reference_id = 1
result = find_ids_within_ten_percentage_threshold(df, reference_id)

# Display the result
print(result)

   id_start
0         1
1         2

In [43]:
import pandas as pd

def unroll_distance_matrix(df) -> pd.DataFrame:
    """
    Unroll a distance matrix to a DataFrame in the style of the initial dataset.

    Args:
        df (pandas.DataFrame): A square DataFrame where both the index and columns represent IDs and
                               the values represent distances.

    Returns:
        pandas.DataFrame: Unrolled DataFrame containing columns 'id_start', 'id_end', and 'distance'.
    """
    # Initialize an empty list to store the unrolled data
    unrolled_data = []
    
    # Iterate over each row and column in the DataFrame to get all combinations of id_start and id_end
    for id_start in df.index:
        for id_end in df.columns:
            if id_start != id_end:  # Exclude rows where id_start == id_end
                distance = df.loc[id_start, id_end]
                unrolled_data.append({'id_start': id_start, 'id_end': id_end, 'distance': distance})
    
    # Convert the unrolled data into a DataFrame
    unrolled_df = pd.DataFrame(unrolled_data)
    
    # Print the unrolled DataFrame
    print(unrolled_df)
    
    return unrolled_df

# Example usage
# Create a sample distance matrix
data = {
    'A': [0, 1, 2],
    'B': [1, 0, 3],
    'C': [2, 3, 0]
}
df_distance_matrix = pd.DataFrame(data, index=['A', 'B', 'C'])

# Call the function
result = unroll_distance_matrix(df_distance_matrix)

  id_start id_end  distance
0        A      B         1
1        A      C         2
2        B      A         1
3        B      C         3
4        C      A         2
5        C      B         3

In [47]:
import pandas as pd

def calculate_distance_matrix(df) -> pd.DataFrame:
    
    # Get unique toll locations (IDs)
    toll_locations = pd.unique(df[['id_start', 'id_end']].values.ravel('K'))
    print("Toll locations:", toll_locations)  # Debugging print
    
    # Initialize a DataFrame with toll locations as both index and columns, and fill with large values
    distance_matrix = pd.DataFrame(float('inf'), index=toll_locations, columns=toll_locations)
    
    # Set the diagonal values to 0 (distance from a toll location to itself is 0)
    for location in toll_locations:
        distance_matrix.loc[location, location] = 0
    
    # Print the initialized matrix
    print("Initialized distance matrix:")
    print(distance_matrix)
    
    # Fill in the known distances from the input DataFrame
    for _, row in df.iterrows():
        id_start = row['id_start']
        id_end = row['id_end']
        distance = row['distance']
        distance_matrix.loc[id_start, id_end] = distance
        distance_matrix.loc[id_end, id_start] = distance  # Ensures the matrix is symmetric
    
    # Print the matrix after filling known distances
    print("Distance matrix after filling known distances:")
    print(distance_matrix)
    
    # Apply the Floyd-Warshall algorithm to calculate the shortest path between all pairs
    for k in toll_locations:
        for i in toll_locations:
            for j in toll_locations:
                distance_matrix.loc[i, j] = min(distance_matrix.loc[i, j], distance_matrix.loc[i, k] + distance_matrix.loc[k, j])
    
    # Print the final distance matrix
    print("Final distance matrix:")
    print(distance_matrix)
    
    return distance_matrix

# Example usage:
# Assuming 'dataset-2.csv' has been loaded into a DataFrame with 'id_start', 'id_end', and 'distance' columns
df = pd.read_csv("C:\Users\adars\OneDrive\Attachments\Desktop\dataset-2.csv")
result = calculate_distance_matrix(df)

KeyError: "None of [Index(['id_start', 'id_end'], dtype='object')] are in the [columns]"